#ifndef _ARDUINO_CONFIG_H_
#define _ARDUINO_CONFIG_H_

#include "sdkconfig.h"

#if !defined(CONFIG_IDF_TARGET_ESP32S3)
#error "This project supports ESP32-S3 only."
#endif

// UART used by Serial / SimpleFOC Commander.
#define CONFIG_ARDUINO_UART_PORT_NUM 0
#define CONFIG_ARDUINO_UART_TXD 43
#define CONFIG_ARDUINO_UART_RXD 44

// I2C master.
#define CONFIG_ARDUINO_I2C_HOST_NUM 0
#define CONFIG_ARDUINO_I2C_SCL 1
#define CONFIG_ARDUINO_I2C_SDA 2
#define CONFIG_ARDUINO_I2C_FREQ_HZ 400000

// SPI master used by the magnetic encoder.
#define CONFIG_ARDUINO_SPI_HOST_NUM 2
#define CONFIG_ARDUINO_SPI_MOSI 11
#define CONFIG_ARDUINO_SPI_MISO 13
#define CONFIG_ARDUINO_SPI_CLK 12
#define CONFIG_ARDUINO_SPI_CS0 10
#define CONFIG_ARDUINO_SPI_BAUD_RATE (10 * 1000 * 1000)

// ADC input GPIO channels.
#define CONFIG_ARDUINO_ADC_GPIO_0 4
#define CONFIG_ARDUINO_ADC_GPIO_1 5
#define CONFIG_ARDUINO_ADC_GPIO_2 6
#define CONFIG_ARDUINO_ADC_UNIT ADC_UNIT_1
#define CONFIG_ARDUINO_ADC_CHANNEL_0 ADC_CHANNEL_3
#define CONFIG_ARDUINO_ADC_CHANNEL_1 ADC_CHANNEL_4
#define CONFIG_ARDUINO_ADC_CHANNEL_2 ADC_CHANNEL_5
#define CONFIG_ARDUINO_ADC_ATTEN ADC_ATTEN_DB_12
#define CONFIG_ARDUINO_ADC_BITWIDTH ADC_BITWIDTH_DEFAULT

// Three-phase FOC driver GPIOs.
#define CONFIG_FOC_MOTOR_U 42
#define CONFIG_FOC_MOTOR_V 41
#define CONFIG_FOC_MOTOR_W 40
#define CONFIG_FOC_MOTOR_EN 39

// ESP32-S3 board status LED GPIO and backend.
#define CONFIG_BLINK_LED_STRIP 1
#define CONFIG_BLINK_GPIO 38
#define CONFIG_BLINK_LED_STRIP_BACKEND_RMT 1
#define CONFIG_BLINK_LED_STRIP_BACKEND_SPI 0

#endif
