#ifndef _ARDUINO_CONFIG_H_
#define _ARDUINO_CONFIG_H_

#include "sdkconfig.h"

#if defined(CONFIG_IDF_TARGET_ESP32)
// FFB ESPNOW
#define CONFIG_ESPNOW_WIFI_MODE_STATION 1
#undef CONFIG_ESPNOW_WIFI_MODE_STATION_SOFTAP
#define CONFIG_ESPNOW_PMK "pmk1234567890123"
#define CONFIG_ESPNOW_LMK "lmk1234567890123"
#define CONFIG_ESPNOW_CHANNEL 1
#define CONFIG_ESPNOW_SEND_DELAY 500
#define CONFIG_ESPNOW_SEND_LEN 64
#define CONFIG_ESPNOW_ENABLE_LONG_RANGE 0
#define CONFIG_ESPNOW_ENABLE_POWER_SAVE 0
#define CONFIG_ESPNOW_WAKE_WINDOW 50
#define CONFIG_ESPNOW_WAKE_INTERVAL 100

// Arduino UART
#define CONFIG_ARDUINO_UART_PORT_NUM 0
#define CONFIG_ARDUINO_UART_BAUD_RATE 115200
#define CONFIG_ARDUINO_UART_TXD 1
#define CONFIG_ARDUINO_UART_RXD 3

// Arduino I2C
#define CONFIG_ARDUINO_I2C_HOST_NUM 0
#define CONFIG_ARDUINO_IIC_SCL 22
#define CONFIG_ARDUINO_IIC_SDA 21

// Arduino SPI
#define CONFIG_ARDUINO_SPI_HOST_NUM 2
#define CONFIG_ARDUINO_SPI_CS0 5
#define CONFIG_ARDUINO_SPI_MISO 19
#define CONFIG_ARDUINO_SPI_MOSI 23
#define CONFIG_ARDUINO_SPI_CLK 18

// Simple FOC
#define CONFIG_FOC_MOTOR_U 14
#define CONFIG_FOC_MOTOR_V 12
#define CONFIG_FOC_MOTOR_W 13
#define CONFIG_FOC_MOTOR_EN 15

// LED
#define CONFIG_BLINK_GPIO 2

#elif defined(CONFIG_IDF_TARGET_ESP32S2)

// FFB ESPNOW
#define CONFIG_ESPNOW_WIFI_MODE_STATION 1
#undef CONFIG_ESPNOW_WIFI_MODE_STATION_SOFTAP
#define CONFIG_ESPNOW_PMK "pmk1234567890123"
#define CONFIG_ESPNOW_LMK "lmk1234567890123"
#define CONFIG_ESPNOW_CHANNEL 1
#define CONFIG_ESPNOW_SEND_DELAY 500
#define CONFIG_ESPNOW_SEND_LEN 64
#define CONFIG_ESPNOW_ENABLE_LONG_RANGE 0
#define CONFIG_ESPNOW_ENABLE_POWER_SAVE 0
#define CONFIG_ESPNOW_WAKE_WINDOW 50
#define CONFIG_ESPNOW_WAKE_INTERVAL 100

// Arduino UART
#define CONFIG_ARDUINO_UART_PORT_NUM 0
#define CONFIG_ARDUINO_UART_BAUD_RATE 115200
#define CONFIG_ARDUINO_UART_TXD 43
#define CONFIG_ARDUINO_UART_RXD 44

// Arduino I2C
#define CONFIG_ARDUINO_I2C_HOST_NUM 0
#define CONFIG_ARDUINO_IIC_SCL 1
#define CONFIG_ARDUINO_IIC_SDA 2

// Arduino SPI
#define CONFIG_ARDUINO_SPI_HOST_NUM 2
#define CONFIG_ARDUINO_SPI_CS0 10
#define CONFIG_ARDUINO_SPI_MISO 13
#define CONFIG_ARDUINO_SPI_MOSI 11
#define CONFIG_ARDUINO_SPI_CLK 12

// Simple FOC
#define CONFIG_FOC_MOTOR_U 42
#define CONFIG_FOC_MOTOR_V 41
#define CONFIG_FOC_MOTOR_W 40
#define CONFIG_FOC_MOTOR_EN 39

// LED
#define CONFIG_BLINK_LED_STRIP 1
#define CONFIG_BLINK_GPIO 18
#define CONFIG_BLINK_LED_STRIP_BACKEND_RMT 1
#define BLINK_LED_STRIP_BACKEND_SPI 0

#elif defined(CONFIG_IDF_TARGET_ESP32S3)
// FFB ESPNOW
#define CONFIG_ESPNOW_WIFI_MODE_STATION 1
#undef CONFIG_ESPNOW_WIFI_MODE_STATION_SOFTAP
#define CONFIG_ESPNOW_PMK "pmk1234567890123"
#define CONFIG_ESPNOW_LMK "lmk1234567890123"
#define CONFIG_ESPNOW_CHANNEL 1
#define CONFIG_ESPNOW_SEND_DELAY 500
#define CONFIG_ESPNOW_SEND_LEN 64
#define CONFIG_ESPNOW_ENABLE_LONG_RANGE 0
#define CONFIG_ESPNOW_ENABLE_POWER_SAVE 0
#define CONFIG_ESPNOW_WAKE_WINDOW 50
#define CONFIG_ESPNOW_WAKE_INTERVAL 100

// Arduino UART
#define CONFIG_ARDUINO_UART_PORT_NUM 0
#define CONFIG_ARDUINO_UART_BAUD_RATE 115200
#define CONFIG_ARDUINO_UART_TXD 43
#define CONFIG_ARDUINO_UART_RXD 44

// Arduino I2C
#define CONFIG_ARDUINO_I2C_HOST_NUM 0
#define CONFIG_ARDUINO_IIC_SCL 1
#define CONFIG_ARDUINO_IIC_SDA 2

// Arduino SPI
#define CONFIG_ARDUINO_SPI_HOST_NUM 2
#define CONFIG_ARDUINO_SPI_CS0 10
#define CONFIG_ARDUINO_SPI_MISO 13
#define CONFIG_ARDUINO_SPI_MOSI 11
#define CONFIG_ARDUINO_SPI_CLK 12

// Simple FOC
#define CONFIG_FOC_MOTOR_U 42
#define CONFIG_FOC_MOTOR_V 41
#define CONFIG_FOC_MOTOR_W 40
#define CONFIG_FOC_MOTOR_EN 39

// LED
#define CONFIG_BLINK_LED_STRIP 1
#define CONFIG_BLINK_GPIO 38
#define CONFIG_BLINK_LED_STRIP_BACKEND_RMT 1
#define BLINK_LED_STRIP_BACKEND_SPI 0

#else
#error "Unsupported target: only ESP32, ESP32S2, ESP32S3 are supported"
#endif

#endif
